## analyse.R
## analyse MCMC output generated by the C code

if (!require("pacman")) install.packages("pacman")
pacman::p_load("smfsb")

out = read.table("fit-bayes.out", header=TRUE)

mcmcSummary(out)
image(cor(out)[ncol(out):1,])
pairs(out[sample(1:10000,1000),],pch=19,cex=0.2)


## eof

