#!/usr/bin/env Rscript
## analyse.R
## analyse MCMC output generated by the Haskell code

if (!require("pacman")) install.packages("pacman")
pacman::p_load("smfsb")

out = read.table("rwmh.mat", header=FALSE)
names(out) = paste0("V", 0:7)

mcmcSummary(out)
image(cor(out)[ncol(out):1,])
pairs(out[sample(1:10000,1000),],pch=19,cex=0.2)


## eof

