#!/usr/bin/env Rscript
## analyse.R
## analyse MCMC output generated by the Python code using R

if (!require("pacman")) install.packages("pacman")
pacman::p_load("arrow", "smfsb")

args = commandArgs(trailingOnly=TRUE)
if (length(args) != 1)
    stop("analyse.R filename.parquet")

fileName = args[1]

out = read_parquet(fileName)

mcmcSummary(out)
image(cor(out)[ncol(out):1,])
pairs(out[sample(1:10000,1000),],pch=19,cex=0.2)


## eof

