#!/usr/bin/env Rscript
## analyse.R
## analyse MCMC output generated by the Scala code

if (!require("pacman")) install.packages("pacman")
pacman::p_load("smfsb")

args = commandArgs(trailingOnly=TRUE)
if (length(args) != 1)
    stop("analyse.R filename.csv")

fileName = args[1]

out = read.csv(fileName, header=TRUE)

mcmcSummary(out)
image(cor(out)[ncol(out):1,])
pairs(out[sample(1:10000,1000),],pch=19,cex=0.2)


## eof

