#!/usr/bin/env Rscript
## analyse.R
## analyse MCMC output generated by the DEX code

if (!require("pacman")) install.packages("pacman")
pacman::p_load("smfsb")

args = commandArgs(trailingOnly=TRUE)
if (length(args) != 1)
    stop("analyse.R filename.tsv")

fileName = args[1]

out = read.table(fileName, header=FALSE)
names(out) = paste0("V", 0:7)

mcmcSummary(out)
image(cor(out)[ncol(out):1,])
pairs(out[sample(1:10000,1000),],pch=19,cex=0.2)


## eof

